<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RAYHAN" failures="1" tests="2" name="test.home.HomeQuoteTest" time="12.419" errors="0" timestamp="2023-02-28T11:39:46 GMT-05:00" skipped="0">
  <testcase classname="test.home.HomeQuoteTest" name="homeQuoteTest" time="8.680">
    <failure message="expected [Verify your city and state] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Verify your city and state] but found []
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.commons.CommonActions.validate(CommonActions.java:19)
at com.objects.AddressPage.verifyCityAndState(AddressPage.java:18)
at test.home.HomeQuoteTest.homeQuoteTest(HomeQuoteTest.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- homeQuoteTest -->
  <system-out>
    <![CDATA[Validating ---> actual: Insurance designed with you in mind*** Expected: Insurance designed with you in mind<br>
[[ChromeDriver: chrome on WINDOWS (065b8a42f5cc7f50ae610ed1b1a7ed8b)] -> xpath: //button[contains(text(),'Start a New Quote')]] ----> has been clicked<br>
54115 --> This value has been passed into -->[[ChromeDriver: chrome on WINDOWS (065b8a42f5cc7f50ae610ed1b1a7ed8b)] -> xpath: //input[@id='uid_60']]<br>
[[ChromeDriver: chrome on WINDOWS (065b8a42f5cc7f50ae610ed1b1a7ed8b)] -> xpath: //div[@value='Home']] ----> has been clicked<br>
[[ChromeDriver: chrome on WINDOWS (065b8a42f5cc7f50ae610ed1b1a7ed8b)] -> class name: LoadingButton__content] ----> has been clicked<br>
Validating ---> actual: *** Expected: Verify your city and state<br>]]>
  </system-out>
  <testcase classname="test.home.HomeQuoteTest" name="nonFunctionalTest" time="3.739"/>
  <system-out>
    <![CDATA[Validation non functional<br>]]>
  </system-out>
</testsuite> <!-- test.home.HomeQuoteTest -->
